server:
  port: 8080
  servlet:
       context-path: /api/gilded-rose 
  tomcat:
        threads:
            max: 200
            min-spare: 25
            
            
#Spring Profile            
spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2-db/gildedrose
    username: gildedrose
    password: gildedrose
    driverClassName: org.h2.Driver
    initialization-mode: always
 
 # The below configuration is for Spring Boot 1.x: & For  Spring Boot 2.x:-> Use server context-path
 # data:
 #   rest:
 #     basePath: /api/gilded-rose  
  
  #Added to take care of Swagger error related to the ant patterns
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
                       
#Springdoc Properties
springdoc:
  api-docs:
    path: /api-docs

#Logger level
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com: DEBUG
    org.hibernate: ERROR
        
management:
  security:
    enabled:
          true  
  endpoints:
    web:
      exposure:
        include: "*" 
  